In [5]:
import pandas as pd
import numpy as np

In [6]:
non_scaled = np.load("../pipelines/processing_embedding_with_reductions/results/analysed_embedding_space/embedding_exploring/artifacts/training_embeddings.npy")
non_scaled

array([[-0.01459145, -0.19270088,  0.35276842, ...,  0.17342624,
         0.08558771, -0.08300032],
       [ 0.03325117, -0.25682452,  0.33800128, ...,  0.20440763,
         0.18756889, -0.17806743],
       [-0.09971829, -0.1048779 ,  0.1468852 , ...,  0.26047587,
         0.0406069 , -0.06569374],
       ...,
       [-0.03602926,  0.02700889,  0.34793895, ...,  0.27018875,
        -0.07373737,  0.10974287],
       [-0.16819562, -0.12916875,  0.14930384, ...,  0.19248518,
         0.12890135,  0.1015609 ],
       [ 0.00564243, -0.06838211,  0.23358513, ...,  0.26192188,
         0.06415277, -0.06910656]], shape=(4193, 320))

In [8]:
non_scaled_jg = np.load("/home/david/Downloads/training_embeddings_not.npy")
non_scaled_jg

array([[-0.01459145, -0.19270086,  0.35276839, ...,  0.17342605,
         0.08558781, -0.08300024],
       [ 0.03325111, -0.25682452,  0.33800137, ...,  0.20440765,
         0.18756899, -0.17806737],
       [-0.0997185 , -0.10487784,  0.14688501, ...,  0.26047584,
         0.04060714, -0.06569372],
       ...,
       [-0.03602929,  0.02700889,  0.34793893, ...,  0.27018887,
        -0.07373732,  0.10974299],
       [-0.16819562, -0.12916893,  0.14930405, ...,  0.19248515,
         0.12890133,  0.10156071],
       [ 0.00564243, -0.06838238,  0.23358533, ...,  0.26192203,
         0.06415257, -0.06910651]], shape=(4193, 320))

In [7]:
scaled = np.load("../pipelines/processing_embedding_with_reductions_normalize/results/analysed_embedding_space/embedding_exploring_normalize/artifacts/training_embeddings.npy")
scaled

array([[-0.00314729, -0.04156449,  0.07609016, ...,  0.03740706,
         0.01846079, -0.0179027 ],
       [ 0.00684718, -0.05288609,  0.06960225, ...,  0.04209224,
         0.03862476, -0.03666819],
       [-0.01762744, -0.01853951,  0.02596524, ...,  0.04604493,
         0.00717818, -0.01161284],
       ...,
       [-0.0066471 ,  0.00498292,  0.06419185, ...,  0.04984758,
        -0.01360393,  0.02024665],
       [-0.03309161, -0.02541328,  0.02937475, ...,  0.03787046,
         0.02536067,  0.01998158],
       [ 0.00102954, -0.01247726,  0.04262082, ...,  0.04779125,
         0.01170556, -0.01260944]], shape=(4193, 320))

In [9]:
scaled_jg = np.load("/home/david/Downloads/training_embeddings_norm.npy")
scaled_jg

array([[-0.00314729, -0.04156449,  0.07609015, ...,  0.03740702,
         0.01846081, -0.01790268],
       [ 0.00684717, -0.05288609,  0.06960227, ...,  0.04209224,
         0.03862478, -0.03666817],
       [-0.01762748, -0.0185395 ,  0.02596521, ...,  0.04604493,
         0.00717822, -0.01161284],
       ...,
       [-0.00664711,  0.00498292,  0.06419186, ...,  0.04984762,
        -0.01360393,  0.02024668],
       [-0.03309161, -0.02541331,  0.02937479, ...,  0.03787045,
         0.02536066,  0.01998154],
       [ 0.00102954, -0.01247731,  0.04262087, ...,  0.04779129,
         0.01170552, -0.01260944]], shape=(4193, 320))